inherit_gem:
  rubocop-infinum: rubocop.yml

require: 
  - rubocop-infinum
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.1

Gemspec/RequiredRubyVersion:
  Enabled: false

Rails:
  Enabled: false

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 5
